### ISSUE TITLE
Internationalization review

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#1107]
Before we hit CR, we need to go through an internationalization review in https://w3c.github.io/i18n-drafts/techniques/shortchecklist

- [x] ... contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),
  - We do not contain any such text
 - [x] ... allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.
   - Not inherently, people can produce text in [WebGL](https://www.khronos.org/registry/webgl/specs/latest/1.0/) that they may display, however.
 - [x] ... allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.
 - Nope
 - [x] ... allows searching or matching of text, including syntax and identifiers
 - Nope
 - [x] ... sorts text
 - Nope
 - [x] ... captures user input
  - **Yes**, but the user input is in the form of gestures and controller actions, not language
 - [x] ... deals with time in any way that will be read by humans and/or crosses time zone boundaries
  - Nope
 - [x] ... allows any character encoding other than UTF-8
  - Nope, we don't handle text at all
 - [x] ... defines markup
  - Nope
 - [x] ... deals with names, addresses, time & date formats, etc
  - Nope
 - [x] ... describes a format or data that is likely to need localisation
  - Nope
 - [ ] ... makes any reference to or relies on any cultural norms
   - _Not that I can think of_. There are "norms" on how an XR device is to be used, but those are set by the XR device and we try to be accomodating to different norms on different devices.

**Comment by toji** [comment]
Seems like an accurate assessment to me. The only thing worth adding is that for "cultural norms" we should consider that to include in this case variations in physical features across different groups, such as height and IPD. (IE: We want to avoid setting defaults that assume, for example, the average North American male IPD.)

There's no area of spec or modules I'm aware of where we set such defaults at this point, though we may inherit some from the users hardware.

**Comment by Manishearth** [comment]
The review was resolved in  w3c/i18n-request#127
