### ISSUE TITLE
tracking Wide Review for Level1 CR

### ISSUE THREAD

**Issue by himorin** [immersive-web/webxr#1114]
Per [Document review](https://www.w3.org/wiki/DocumentReview#Horizontal_Groups):
 
* [ ]  [I18N review](https://github.com/w3c/i18n-request/issues/127)
  * [i18n self review](https://github.com/immersive-web/webxr/issues/1107)
* [ ]  [TAG review](https://github.com/w3ctag/design-reviews/issues/545)
* [ ]  [Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0016.html)
* [ ]  Accessibility review  (not yet?)
* [x]  [Security review](https://lists.w3.org/Archives/Public/public-web-security/2020Aug/0001.html)
* [ ]  To chairs list (not yet?)
* wide groups (will we?)
  * MEIG
  * Khronos

**Comment by himorin** [comment]
seems still no request for re-review to apa: https://lists.w3.org/Archives/Public/public-apa/2020Sep/subject.html (cc: @Manishearth , @toji )

**Comment by Manishearth** [comment]
Yeah, I plan to do it

**Comment by himorin** [comment]
> Yeah, I plan to do it

Added a link to public-apa mail archive to the list. (just note)
